import os
from datetime import datetime
required="pip install random"
apt="pkg install neofetch"
os.system (apt)# delete line if already in sys
#os.system (required)# delete line if already in sys
os.system ("clear")
import random
from random import randint as run

g,r,p='\033[1;32m','\033[1;31m','\033[1;35m'
b,y,nn='\033[1;36m','\033[1;33m',list("0123456789")
TZ,h= str(datetime.now().strftime('%H:%M')),16

os.system ("clear")
os.system ("neofetch")
print(b+" CC GENERATOR By @Gβε₷hMod \n")
bb=input("Enter Bin [RND:Press Enter]>>> ")
mm=input("Enter Month [RND:Press Enter]>>> ")
yy=input("Enter year [RND:Press Enter]>>> ")
cc=input("Enter Cvv [RND:Press Enter]>>> ")
hh=input("Enter No [DEFAULT 100]>>> ")
h=input("Enter CC LENGTH [DEFAULT 16]>>> ");print("\n")

try:
  hh=int(hh)
except:
  hh=100
try:
  h=int(h)
except:
  h=16
if bb in (""," ","  ","   "):
  print (p+"∂ѳท'τ Բષ૮ઝ ખ¡τђ ʍ૯ \n")
  bb='{0}{1}'.format(str(run(4,6)),str(run(3,9)))
else:
  bb==bb

def alive(card_number):
  sum = 0
  num_digits = len(card_number)
  oddeven = num_digits & 1
  for count in range(0, num_digits):
    digit = int(card_number[count])
    if not (( count & 1 ) ^ oddeven ):
      digit = digit * 2
    if digit > 9:
      digit = digit - 9
      sum = sum + digit
    return ( (sum % 10) == 0 )

def bins(gen):
  if len(str(gen))<h+1:
    a,c=h-len(str(gen)),""
    b=gen+("x"*a)
    for x in range(h):
      if b[x] in ("0","1","2","3","4","5","6","7","8","9"):
        c = c+b[x]
        continue
      elif b[x] in ("x"):
        c = c+str(run(0,9))
  else:
    print(r+f"404 DEAD {bb}");exit()
  alive(c)
  c = c
  return(c)

def mont(mm):
  if len(str(mm))==0:
    mm=str(run(1,12))
    if int(mm)<10:
      mm=("0"+str(mm))
  elif mm=='1':
    mm=mm+str(run(0,2))
  else:
    if int(mm)<10:
      mm=("0"+str(mm))
  return mm

def year(yy):
  if len(str(yy))==0:
    yy="202"+str(run(1, 9))
  elif len(str(yy))==1:
    yy="202"+yy
  elif len(str(yy))==2:
    yy="20"+yy
  return yy

def cvv(cc):
  if str(bb[0])=='3':
    a=4-len(str(cc))
    b=random.choices(nn,k=a)
    c=cc+"".join(b)
  else:
    a=3-len(str(cc))
    b=random.choices(nn,k=a)
    c=cc+"".join(b)
  return c

file=open(("creditcard"+TZ+".txt"),"w")
for i in range(hh):
  toto=bins(bb)+"|"+mont(mm)+"|"+year(yy)+"|"+cvv(cc)
  print(g+toto)
  file.write(toto+"\n")
  file.flush()
file.write("\nCC GENERATED BY Gβε₷ἭMod \n")
file.close()
print("\nGENERATED successfully!")
