#Python 4
#GbeshMod

import os

#required="pip install random"
#apt="pkg install neofetch"
#os.system (apt)# delete line if already in sys
#os.system (required)# delete line if already in sys
os.system ("clear")
import random
from datetime import datetime
from random import randint as run
logo = """
\033[1;92m	
\033[1;97m                      :::!~!!!!!:.
\033[1;97m                  .xUHWH!! !!?M88WHX:.
\033[1;97m                .X*#M@$!!  !X!M$$$$$$WWx:.
\033[1;97m               :!!!!!!?H! :!$!$$$$$$$$$$8X:
\033[1;97m              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:
\033[1;97m             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!
\033[1;97m             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!
\033[1;97m               !:~~~ .:!M"T#$$$$WX??#MRRMMM!
\033[1;91m               ~?WuxiW*`   `"#$$$$8!!!!??!!!
\033[1;91m             :X- M$$$$       `"T#$T~!8$WUXU~
\033[1;91m            :%`  ~#$$$m:        ~!~ ?$$$$$$
\033[1;91m          :!`.-   ~T$$$$8xx.  .xWW- ~""##*"
\033[1;97m.....   -~~\033[1;91m:<` !    ~?T#$$@@W@*?$$      /`
\033[1;97mW$@@M!!! .!~~ \033[1;91m!!     .:XUW$W!~ `"~:    :
\033[1;97m#"~~`.:x%`!!  \033[1;91m!H:   !WM$$$$Ti.: .!WUn+!`
\033[1;97m:::~:!!`:X~ .:\033[1;92m ?H.!u "$$$B$$$!W:U!T$$M~
\033[1;97m.~~   :X@!.-~   \033[1;92m?@WTWo("*$$$W$TH$! `
\033[1;97mWi.~!X$?!-~    : \033[1;92m?$$$B$Wu("**$RM!
\033[1;97m$R@i.~~ !     :   \033[1;92m~$$$$$B$$en:``     
\033[1;97m?MXT@Wx.~    :     \033[1;92m~"##*$$$$M~   
\033[1;47m                  \033[1;31mGbesh Mod                 \033[1;0m     
\033[1;97m✮❂❂❂❂❂❂❂❂❂❂❂❂✮\033[1;91mWhite-Tiger-mail\033[1;97m✮❂❂❂❂❂❂❂❂❂❂❂❂✮"""
g,r,p='\033[1;32m','\033[1;31m','\033[1;35m'
b,y,nn='\033[1;36m','\033[1;33m',list("0123456789")
TZ,h= str(datetime.now().strftime('%H:%M')),10

os.system ("clear")
print(logo) 
#os.system ("neofetch")
print(y+"\n PHONE Number "+r+"GENERATOR"+g+" By @Gβε₷hMod \n")
aa=input(b+"Enter Country code Number [RND:Press Enter]>>> ")
bb=input("Enter Phone Number [RND:Press Enter]>>> ")
h=input("Enter P Number LENGTH [DEFAULT 10]>>> ")
pas=input("Enter Password LENGTH [DEFAULT 6]>>> ")
hh=input("Enter No [DEFAULT 100]>>> ");print("\n")

try:
  hh=int(hh)
except:
  hh=100
try:
  h=int(h)
except:
  h=10
try:
  pas=int(pas)
except:
  pas=6
 
if aa in (""," ","  ","   "):
  print (p+"∂ѳท'τ Բષ૮ઝ ખ¡τђ ʍ૯ \n")
  aa='+{0}{1}'.format(str(run(1,9)),str(run(1,99)))
else:
  aa=="".join(aa)

if bb in (""," ","  ","   "):
  bb='0{0}{1}'.format(str(run(1,9)),str(run(1,99)))
else:
  bb=="".join(bb)

def phonn(cc):
  if str(bb[0])=='0':
    aaa=pas-len(str(bb))
    bbb=random.choices(nn,k=aaa)
    ccc=bb+''.join(bbb)
    a=len(str(ccc))-len(str(h))
    ab=random.choices(nn,k=a)
    ac=list(ccc)
    ac.remove('0')
    ba=''.join(ac)
    bc=ba+"".join(ab)
    cz=aa+bc
    c=cz+":"+str(ccc)
  else:
    aaa=pas-len(str(bb))
    bbb=random.choices(nn,k=aaa)
    ccc=bb+''.join(bbb)
    a=len(str(ccc))-len(str(h))
    ab=random.choices(nn,k=a)
    ac=list(ccc)
    ba=''.join(ac)
    bc=ba+"".join(ab)
    cz=aa+bc
    c=cz+":"+str(ccc)
  return c
  
  
file=open(("phonenumber"+TZ+".txt"),"w")
for i in range(hh):
  toto=phonn(aa)
  print(g+toto)
  file.write(toto+"\n")
  file.flush()
file.write("\nGENERATED BY Gβε₷ἭMod \n")
file.close()
print("\nGENERATED successfully!")

